variables:
  nproc: "1"


before_script:
   - nproc=`grep -c '^processor' /proc/cpuinfo`
   - echo "nproc = $nproc"
   - export LD_LIBRARY_PATH=$HOME/boost_1_61_0/stage/lib/:$LD_LIBRARY_PATH
   - mkdir build && cd build/
   

stages:
  - compile
  - unit_test
  - rimea

compile:
  stage: compile
  script:
    - cmake -DBUILD_TESTING=ON -DBoost_NO_SYSTEM_PATHS=true -DBOOST_ROOT=~/boost_1_61_0 ..
    - make -j$nproc
    - echo "compile in $PWD"

  artifacts:
    untracked: true
    paths:
      - build
      
    

test:
 stage: unit_test 
 script:
    - echo "unit_test in $PWD"
    - ctest -R Boost

verify:
  stage: rimea
  script:
    - echo "curl -X POST -F token=$TOKEN -F ref=develop https://gitlab.version.fz-juelich.de/api/v3/projects/262/trigger/builds"| at 22:00
    - ctest -R rimea
  only: 
    - develop

after_script:
  - echo "End CI"