# Simple debug build. Requires OpenCV2 lib, therefore
# this job can only be performed by runners with the
# "opencv2" tag
before_script:
  - mkdir build && cd build/

compile_jpscore:
  script:
    - cmake .. -DBUILD_TESTING=ON
    - make -j$(nproc) 
    - ctest -R Boost