# compile jpscore and run light tests
before_script:
   - nproc=`grep -c '^processor' /proc/cpuinfo`
   - echo "nproc = ${nproc}"
   - mkdir build && cd build/

build:
  script:
    - cmake -DBUILD_TESTING=ON -DBoost_NO_SYSTEM_PATHS=true -DBOOST_ROOT=~/boost_1_61_0 .. 
    - make -j${nproc}
    - ctest -R Boost                         
