language: cpp
os:
    - linux
    # - osx

branches:
  only:
    - master
    - v0.8
    
compiler:
    - gcc
    # - clang
  
before_script:
    - source .travis_before_script.bash
  
before_install:
    - source .travis_before_install.bash          

install:
    - source .travis_install.bash

script:
    - $CXX --version
    - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov
    - mkdir build && cd build
    - cmake -DBUILD_TESTING=ON ..
    - make

after_success:
    - make cov
#    - ctest -R rimea
#    - ctest -R juelich
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         codecov;
      fi   
    
notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always
     