language: cpp

branchs:
  - master
  - v0.8
  - refactor_travis

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - apokluda-boost1.53
      - h-rayflood-llvm
    packages:
      - g++-4.8
      - clang++-3.4
      - libboost1.53-all-dev
      - cmake
      - doxygen
      - lcov

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      script:
        - $CXX --version
        - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov
        - mkdir build && cd build
        - cmake -DBUILD_TESTING=ON ..
        - make
        - sudo pip install codecov
        - sudo pip install numpy
        - make cov
        # - ctest -R rimea
        # - ctest -R juelich
        - codecov

    # - os: osx
    #   compiler: clang
    #   script:

notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always
