language: cpp
dist: bionic

git:
  depth: 1
  quiet: true

matrix:
  include:
    - name: linux (clang8)
      os: linux
      env: TOOLCHAIN=clang
      script:
       - ./scripts/setup-deps.sh
       - mkdir build && cd build
       - cmake  .. -DCMAKE_PREFIX_PATH=$(pwd)/../deps -DBUILD_CPPUNIT_TEST=ON -DBUILD_TESTING=ON -DAIROUTER=ON -DJPSFIRE=ON
       - make -j $(nproc)

    - name: linux (gcc9)
      os: linux
      env: TOOLCHAIN=gcc
      script:
       - ./scripts/setup-deps.sh
       - mkdir build && cd build
       - cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../deps -DBUILD_CPPUNIT_TEST=ON -DBUILD_TESTING=ON -DAIROUTER=ON -DJPSFIRE=ON
       - make -j $(nproc)

before_install:
    - source .travis_before_install.bash

install:
    - source .travis_install.bash
