language: cpp
  
before_script:
  - brew update
  - brew unlink boost
  - brew install boost
  - brew install cmake

script:
    - cmake .. -DBUILD_TESTING=ON
    - make -j$(nproc)     
    - ctest -R Boost 

notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always

