language: cpp
os:
  - linux
  # - osx

branches:
  only:
    - master
    - v0.8
    - refactor_travis
    
compiler:
  - gcc
  # - clang
  
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       sudo add-apt-repository -y ppa:apokluda/boost1.53;
       sudo apt-get update;
       sudo apt-get install libboost1.53-all-dev;
       sudo apt-get install doxygen lcov;
       sudo pip install codecov numpy;
    fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
       brew update;   
       brew unlink boost;
       brew install boost doxygen lcov;
       sudo pip install numpy;
    fi

before_install:
  # g++4.8.1
  # clang 3.4
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       if [ "$CXX" == "g++" ]; then
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
       elif [ "$CXX" == "clang++" ]; then
          sudo add-apt-repository -y ppa:h-rayflood/llvm;
       fi
       sudo apt-get update -qq;
    fi
    
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       if [ "$CXX" = "g++" ]  && 
          sudo apt-get install -qq g++-4.8;
          export CXX="g++-4.8";
       elif [ "$CXX" == "clang++" ]; then
          sudo apt-get install --allow-unauthenticated -qq clang-3.4;
          export CXX="clang++-3.4";
       fi          

script:
    - $CXX --version
    - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov
    - mkdir build && cd build
    - cmake -DBUILD_TESTING=ON ..
    - make

after_success:
    - make cov
#    - ctest -R rimea
#    - ctest -R juelich
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         codecov;
      fi   
    
notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always
     